#ifndef J_FILTERDXFRW_GLOBAL_H
#define J_FILTERDXFRW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(J_FILTERDXFRW_LIBRARY)
#  define J_FILTERDXFRWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define J_FILTERDXFRWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // J_FILTERDXFRW_GLOBAL_H
