/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jlibdxfrw */

#ifndef _Included_Jlibdxfrw
#define _Included_Jlibdxfrw
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_no_demas_dcad_dxf_Jlibdxfrw_read
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
